### ISSUE TITLE
month must be in 1..12

### ISSUE THREAD

**Issue by Soneji** [milesmcc/shynet#191]
Hi

My docker instance has stopped working I am not sure why

```py
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    | ERROR Internal Server Error: /dashboard/
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    | Traceback (most recent call last):
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     response = get_response(request)
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     return self.dispatch(request, *args, **kwargs)
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     return super().dispatch(request, *args, **kwargs)
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     return handler(request, *args, **kwargs)
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/list.py", line 157, in get
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     context = self.get_context_data()
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/src/shynet/dashboard/views.py", line 36, in get_context_data
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     data = super().get_context_data(**kwargs)
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/src/shynet/dashboard/mixins.py", line 64, in get_context_data
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     data["date_ranges"] = self.get_date_ranges()
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |   File "/usr/src/shynet/dashboard/mixins.py", line 50, in get_date_ranges
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    |     'start': now.replace(day=1, month=now.month - 1),
shynet_shynet.1.npk40tgft9v5@ubuntu-2gb-nbg1-2    | ValueError: month must be in 1..12
```

This is the error I have in my logs

**Comment by milesmcc** [comment]
Hi! Please update to v0.12.0. This issue is fixed. Thanks!

**Comment by milesmcc** [comment]
Feel free to reopen if that does not solve your issue.

**Comment by Soneji** [comment]
```
root@ubuntu-2gb-nbg1-2:~/shynet# docker image ls
REPOSITORY                      TAG             IMAGE ID       CREATED         SIZE
postgres                        <none>          58bff7631346   8 days ago      371MB
milesmcc/shynet                 latest          e53cab94e9b6   11 days ago     1.75GB
```

I think I am on the latest one but the issue is still here, it also won't let me reopen the issue

**Comment by milesmcc** [comment]
Same exact error as before (`ValueError: month must be in 1..12`)?

**Comment by Soneji** [comment]
Yes, I was already on the latest
